version: "3.8"
services:
  moodle:
    build: ./docker
    ports:
      - "80:80"
    environment:
      - DB_TYPE=mariadb
      - DB_HOST=db
      - DB_PORT=3306
      - DB_NAME=moodle_calculo
      - DB_USERNAME=moodle_calculo
      - DB_PASSWORD=secret
      - DB_PREFIX=mdl_
      - WWWROOT=http://localhost
      - SSLPROXY=0
      - DATAROOT=/var/lib/moodledata
    volumes:
      - "./moodle:/var/www/html"
      - "./moodledata:/var/lib/moodledata"
    depends_on:
      - db
    deploy:
      resources:
        limits:
          cpus: "2.0"
          memory: 1G
  db:
    image: mariadb
    environment:
      - MARIADB_ROOT_PASSWORD=root
      - MARIADB_DATABASE=moodle_calculo
      - MARIADB_USER=moodle_calculo
      - MARIADB_PASSWORD=secret
    command: --innodb_large_prefix --innodb-file-format=barracuda
    volumes:
     # - "./moodle_calculo.sql:/docker-entrypoint-initdb.d/moodle_calculo.sql"
     - "./data:/var/lib/mysql"
    deploy:
      resources:
        limits:
          cpus: "2.0"
          memory: 1G
