version: "3.8"
services:
  moodle:
    build: ./moodle-docker
    ports:
      - "80:80"
    environment:
      - DB_HOST=db
      - DB_PORT=3306
      - DB_NAME=moodle_coresearch
      - DB_USERNAME=moodle_coresearch
      - DB_PASSWORD=HsGf2mDLF7HRMey7
      - DB_PREFIX=mdl_
      - WWWROOT=http://co-research.sobral.ufc.br 
      - SSLPROXY=0
      - DATAROOT=/var/www/html/moodledata
    volumes:
      - "./moodle-coresearch:/var/www/html"
    depends_on:
      - db
  db:
    image: mysql:5.7.41
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    environment:
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_DATABASE=moodle_coresearch
      - MYSQL_USER=moodle_coresearch
      - MYSQL_PASSWORD=HsGf2mDLF7HRMey7
    volumes:
      - "./moodle_coresearch.sql:/docker-entrypoint-initdb.d/moodle_coresearch.sql"
      - "./data:/var/lib/mysql"
    ports:
      - "3306:3306"
